name: CI Pipeline

on:
  push:
    branches:
      - testing  # Trigger when changes are pushed to the testing branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/  # Assuming your tests are in the tests/ directory

  build_and_push_docker:
    needs: test  # This job will only run after the test job succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t yourusername/yourimage:latest .

      - name: Log in to DockerHub
        run: |
          echo ${{ secrets.DOCKER_USERNAME }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push yourusername/yourimage:latest
